// Generated by https://quicktype.io

export interface IRolModulo {
  id_modulo: number;
  modulo:    Modulo;
}

export interface Modulo {
  nombre:     string;
  icono:      string;
  sub_modulo: SubModulo[];
}

export interface SubModulo {
  id:        number;
  id_modulo: number;
  nombre:    string;
  url:       string;
}
