// Generated by https://quicktype.io

import { ICatEstado } from "../general";

export interface IRolModulo {
  id_modulo: number;
  modulo: Modulo;
}

export interface Modulo {
  nombre: string;
  icono: string;
  sub_modulo: SubModulo[];
}

export interface SubModulo {
  id: number;
  id_modulo: number;
  nombre: string;
  url: string;
}

export interface IRol {
  id: number;
  nombre: string;
  id_estado: number;
  cat_estado?: ICatEstado; 
}
